#!/usr/bin/env bash

set -e

base_dir=$(cd $(dirname $0); cd ..; pwd)

cd $base_dir

scripts/create-internal-pki

cd $base_dir/pki

pushd ..
kubectl create secret generic license --from-file=license-enterprise.pem
popd
kubectl create secret tls tls-web --cert=proxy-server.pem --key=proxy-server-key.pem
kubectl create configmap ca-certs --from-file=ca.pem

cd $base_dir

helm upgrade --install --reset-values -f minikube.values.yaml --recreate-pods --wait teleport ./

pod=$(kubectl get po | grep teleport | grep Running | cut -d' ' -f1)

kubectl exec -it $pod -- bash -c "tctl users add --roles=admin $USER" | tee tctl.log

kubectl port-forward $pod 3022 3023 3024 3025 3026 3080 1>&2 > port-forward.log &
pid=$!

echo "`kubectl port-forward` is running in process $pid"
echo "run \"kill $pid\" to stop"

sudo hostess add teleport.example.com 127.0.0.1

signup_url=$(grep https:// tctl.log)

open $signup_url

# Use the our own CA cert as the only trusted root CA cert
# Workaround for https://github.com/gravitational/teleport/issues/2042
sudo mkdir -p /var/lib/teleport
sudo chown $USER /var/lib/teleport
cp pki/ca.pem /var/lib/teleport/webproxy_cert.pem
